import { test, expect } from '@playwright/test';

const v1 = '00000000-0000-4000-8000-000000000021';
const v2 = '00000000-0000-4000-8000-000000000022';
const caseId = '00000000-0000-4000-8000-000000000010';

test('actual advisor API and Strands: cold bootstrap, evidence, drafts, comparison, persistence and private browser isolation', async ({ page, browser }) => {
  const errors: string[] = [];
  const failed: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('response', response => { if (response.url().includes('/api/advisor/') && response.status() >= 400) failed.push(`${response.status()} ${response.url()}`); });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`/advisor/clients?advisor_demo=server&server_version=${v1}`);
  await expect(page.getByText('Connected · private history saved on server', { exact: true })).toBeVisible();
  await expect(page.getByText(/Simulated model · no AWS calls/)).toBeVisible();
  await expect(page.getByRole('article', { name: 'Server packet version 1' })).toContainText('$240,000');
  await page.getByRole('button', { name: 'Missing or conflicting evidence', exact: true }).click();
  const answer = page.locator('.advisor-chat-message').filter({ hasText: 'Relay advisor AI' });
  await expect(answer).toContainText('$240,000');
  await expect(answer).toContainText('$280,000');
  await expect(answer).toContainText('Reserve target: not provided.');
  const citation = page.getByRole('link', { name: 'Forecast assumptions.pdf · v1 · p. 1', exact: true });
  const popupPromise = page.waitForEvent('popup');
  await citation.click();
  const popup = await popupPromise;
  await expect(popup.locator('body')).toContainText('2026 annual revenue forecast: $280,000.');
  await popup.close();
  const draft = page.getByRole('textbox', { name: 'Private follow-up draft', exact: true }).first();
  await draft.fill('Please confirm the reserve target with a supporting source.');
  await page.reload();
  await expect(answer).toHaveCount(1);
  await expect(draft).toHaveValue('Please confirm the reserve target with a supporting source.');
  await page.screenshot({ path: test.info().outputPath('advisor-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('textbox', { name: 'Ask about shared packet v1', exact: true }).scrollIntoViewIfNeeded();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.screenshot({ path: test.info().outputPath('advisor-narrow.png'), fullPage: true });
  await page.getByRole('combobox', { name: 'Compare shared version', exact: true }).selectOption(v2);
  await expect(page.getByText('No private messages for this server packet yet.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Compare shared versions', exact: true }).click();
  await expect(answer).toContainText('$260,000');
  await expect(page.getByRole('link', { name: 'Founder planning packet · v1 · packet', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Founder planning packet · v2 · packet', exact: true })).toBeVisible();
  await page.getByRole('combobox', { name: 'Server shared packet', exact: true }).selectOption(v2);
  await expect(page.getByRole('article', { name: 'Server packet version 2' })).toContainText('$260,000');
  await expect(answer).toHaveCount(0);
  await page.getByRole('combobox', { name: 'Server shared packet', exact: true }).selectOption(v1);
  await expect(answer).toHaveCount(1);
  await expect(answer).toContainText('Reserve target: not provided.');
  const second = await browser.newContext();
  const secondPage = await second.newPage();
  await secondPage.goto(`http://127.0.0.1:5201/advisor/clients?advisor_demo=server&server_version=${v1}`);
  await expect(secondPage.getByText('No private messages for this server packet yet.', { exact: true })).toBeVisible();
  await expect(secondPage.locator('.advisor-chat-message')).toHaveCount(0);
  await second.close();
  expect(errors).toEqual([]);
  expect(failed).toEqual([]);
});

test('actual advisor server rejects unassigned cases, unshared versions and missing CSRF', async ({ request }) => {
  const session = await request.get('/api/advisor/session');
  expect(session.ok()).toBe(true);
  const data = await session.json() as { csrf_token: string; workspace: { versions: { id: string; hash: string }[] } };
  const headers = { 'X-CSRF-Token': data.csrf_token, 'Idempotency-Key': 'forged-case' };
  const body = { versions: [data.workspace.versions[0]] };
  const foreign = await request.post('/api/advisor/cases/not-assigned/conversations', { headers, data: { versions: body.versions.map(({ id, hash }) => ({ id, hash })) } });
  expect(foreign.status()).toBe(404);
  const unshared = await request.post(`/api/advisor/cases/${caseId}/conversations`, { headers, data: { versions: [{ id: '00000000-0000-4000-8000-000000000023', hash: 'f'.repeat(64) }] } });
  expect(unshared.status()).toBe(409);
  const csrf = await request.post(`/api/advisor/cases/${caseId}/conversations`, { headers: { 'Idempotency-Key': 'no-csrf' }, data: { versions: body.versions.map(({ id, hash }) => ({ id, hash })) } });
  expect(csrf.status()).toBe(403);
});
