"""Materialize the seven bounded advisor seed records in S3 and extract with Textract.

Prepare is offline. --upload-extract explicitly performs cloud writes and billable analysis.
Uses an existing AWS CLI login; never reads credential files or .env files.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
import tempfile
from typing import Any

from app.advisor.cloud_documents import install_records, normalize, synthetic_pdf
from app.advisor.store import AdvisorStore, digest


class AwsCli:
    def __init__(self, executable: str, profile: str, region: str) -> None:
        self.prefix = [executable, "--profile", profile, "--region", region, "--no-cli-pager"]

    def run(self, args: list[str], data: bytes | None = None) -> bytes:
        result = subprocess.run([*self.prefix, *args], input=data, capture_output=True, timeout=90, check=False)
        if result.returncode:
            # CLI service errors are useful; do not emit the environment or credential process output.
            error = result.stderr.decode(errors="replace")
            code = "NOT_FOUND" if "NoSuchKey" in error or "404" in error else "AWS_REQUEST_FAILED"
            raise RuntimeError(code)
        return result.stdout

    def get(self, bucket: str, key: str) -> bytes | None:
        try:
            return self.run(["s3", "cp", f"s3://{bucket}/{key}", "-", "--only-show-errors"])
        except RuntimeError as exc:
            if str(exc) == "NOT_FOUND":
                return None
            raise

    def put(self, bucket: str, key: str, body: bytes, content_type: str) -> None:
        self.run(["s3", "cp", "-", f"s3://{bucket}/{key}", "--content-type", content_type,
                  "--only-show-errors"], body)

    def analyze(self, bucket: str, key: str) -> dict[str, Any]:
        return json.loads(self.run(["textract", "analyze-document", "--document",
                                   json.dumps({"S3Object": {"Bucket": bucket, "Name": key}}),
                                   "--feature-types", "FORMS", "TABLES", "--output", "json"]))


def prepare(directory: Path) -> list[dict[str, Any]]:
    directory.mkdir(parents=True, exist_ok=True)
    records = []
    # Always derive from a fresh seed, never reinterpret a prior OCR/import as new source data.
    with tempfile.TemporaryDirectory(prefix="relay-synthetic-") as scratch:
        store = AdvisorStore(str(Path(scratch) / "seed.sqlite3"))
        with store.connection() as db:
            for kind, table in (("packet", "advisor_packets"), ("source", "advisor_sources")):
                for row in db.execute(f"SELECT * FROM {table} ORDER BY id"):
                    title = f'{row["title"]} v{row["version"]}' if kind == "packet" else Path(row["name"]).stem
                    filename = f'planning-packet-v{row["version"]}.pdf' if kind == "packet" else f'{title}.pdf'
                    text = row["body"].decode()
                    if text.startswith("Synthetic excerpt"):
                        text = "\n".join(text.splitlines()[1:])
                    original = synthetic_pdf(title, text)
                    path = directory / filename
                    path.write_bytes(original)
                    records.append({"id": row["id"], "kind": kind, "filename": filename, "original": original})
    return records


def ingest(records: list[dict[str, Any]], aws: AwsCli, bucket: str, store: AdvisorStore) -> list[dict[str, Any]]:
    for record in records:
        original = record["original"]
        key = f'synthetic-advisor/v1/{record["id"]}/{digest(original)}/original.pdf'
        existing = aws.get(bucket, key)
        if existing is None:
            aws.put(bucket, key, original, "application/pdf")
        downloaded = aws.get(bucket, key)
        if downloaded != original:
            raise ValueError("S3 original download does not match generated bytes")
        result_key = key.removesuffix("original.pdf") + "textract.json"
        raw = aws.get(bucket, result_key)
        response = json.loads(raw) if raw else aws.analyze(bucket, key)
        extraction = normalize(response, filename=record["filename"], original=original)
        if not raw:
            aws.put(bucket, result_key, json.dumps(response).encode(), "application/json")
        record.update(bucket=bucket, key=key, extraction=extraction)
        print(json.dumps({"document": record["filename"], "s3_key": key, "pages": extraction["pages"],
                          "lines": len(extraction["lines"]), "fields": len(extraction["fields"]),
                          "tables": len(extraction["tables"]), "cached_extraction": bool(raw)}), flush=True)
    install_records(store, records)
    return [{"id": r["id"], "filename": r["filename"], "key": r["key"],
             "original_sha256": digest(r["original"]), "extraction": r["extraction"]} for r in records]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--database", type=Path)
    parser.add_argument("--bucket", default="relay-documents-576248046713")
    parser.add_argument("--region", default="us-east-1")
    parser.add_argument("--profile", default="relay-hackathon")
    parser.add_argument("--aws-cli", default="aws")
    parser.add_argument("--upload-extract", action="store_true")
    args = parser.parse_args()
    if args.upload_extract and args.database is None:
        parser.error("--database is required for explicit import")
    records = prepare(args.output)
    if args.upload_extract:
        results = ingest(records, AwsCli(args.aws_cli, args.profile, args.region), args.bucket,
                         AdvisorStore(str(args.database)))
        (args.output / "manifest.json").write_text(json.dumps(results, indent=2))
        print(f'Imported {len(results)} S3 originals and Textract results into {args.database}', flush=True)
    else:
        print(f'Prepared {len(records)} synthetic PDFs offline in {args.output}')
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
