import { useEffect, useRef, useState } from 'react';
import { useLocation, useSearchParams } from 'react-router-dom';
import type { ReactNode, FormEvent } from 'react';
import { useDraft, useRelay } from './context';
import { streamChat } from './relayApi';
import { AgentStatus, Badge, Button, CitationLink, Icon } from './ui';
export function Conversation({large=false,humanOnly=false,privateOnly=false,children}:{children?:ReactNode;large?:boolean;humanOnly?:boolean;privateOnly?:boolean}):ReactNode{
 const {snapshot,role,busy,run}=useRelay();const [params]=useSearchParams();const [audience,setAudience]=useState<'private_ai'|'human'>(!privateOnly&&(humanOnly||params.get('audience')==='human')?'human':'private_ai');const [text,setText]=useDraft('message:'+snapshot?.id+':'+audience);const [preview,setPreview]=useState(false);
 const [attachments,setAttachments]=useState<string[]>([]);const [choosing,setChoosing]=useState(false);
 // Live AI reply being streamed from the backend; null when idle.
 const [streaming,setStreaming]=useState<string|null>(null);const [chatError,setChatError]=useState<string|null>(null);const stream=useRef<AbortController|null>(null);
 const location=useLocation();
 useEffect(()=>{if(location.hash===`#message-${large?'main':'side'}`){const composer=document.getElementById(`message-${large?'main':'side'}`);composer?.focus();composer?.scrollIntoView?.({block:'center'});}},[location,large]);
 useEffect(()=>{if(!privateOnly&&params.get('audience')==='human'){setAudience('human');setAttachments([]);setChoosing(false);setPreview(false);}},[params,privateOnly]);
 useEffect(()=>{const id=params.get('message');if(id)document.getElementById('message-'+id)?.scrollIntoView?.({block:'center'});},[params,snapshot]);
 useEffect(()=>()=>stream.current?.abort(),[]);
 // Keep the newest message (and the streaming reply) in view, unless a specific message was linked.
 const list=useRef<HTMLDivElement>(null);const messageCount=snapshot?.messages.length??0;
 useEffect(()=>{if(params.get('message'))return;const el=list.current;if(el)el.scrollTop=el.scrollHeight;},[messageCount,streaming,audience,params]);
 if(!snapshot)return null;const me=role==='founder'?snapshot.founder:snapshot.advisors[0];const other=role==='founder'?snapshot.advisors[0]:snapshot.founder;
 const attachableSources=snapshot.sources.filter(source=>audience==='private_ai'||role==='advisor'||snapshot.grants.some(grant=>grant.advisor_id===other.id&&grant.source_ids.includes(source.id)));
 const messages=snapshot.messages.filter(m=>audience==='private_ai'?m.audience.kind==='private_ai':m.audience.kind==='human');
 const replying=streaming!==null;
 const reply=async(prompt:string):Promise<void>=>{
  const c=new AbortController();stream.current=c;let partial='';setStreaming('');setChatError(null);
  try{await streamChat(`${role}-${snapshot.id}`,prompt,chunk=>{partial+=chunk;setStreaming(partial);},c.signal);}
  catch(error:unknown){if(!c.signal.aborted)setChatError(error instanceof Error?error.message:'The assistant could not reply.');}
  if(partial.trim())await run({kind:'ai_reply',text:partial.trim()},{silent:true});
  if(stream.current===c)stream.current=null;setStreaming(null);
 };
 const send=async(e?:FormEvent):Promise<void>=>{e?.preventDefault();if(audience==='human'&&!preview){setPreview(true);return;}const prompt=text;const ok=await run({kind:'message',expected_revision:snapshot.revision,text,attachments,audience:audience==='private_ai'?{kind:'private_ai'}:{kind:'human',recipient_id:other.id},confirmed:audience==='human'},{silent:audience==='private_ai'});if(ok){setText('');setPreview(false);setAttachments([]);setChoosing(false);if(audience==='private_ai')await reply(prompt);}};
 return <section className={`panel conversation ${large?'conversation-large':''}`} aria-label="Conversation"><AgentStatus/><div className="audience-control"><label>Audience<select aria-label="Message audience" value={audience} onChange={e=>{setAudience(e.target.value as 'private_ai'|'human');setPreview(false);setAttachments([]);setChoosing(false);setChatError(null);}} disabled={busy||replying}>{!humanOnly&&<option value="private_ai">Private AI conversation</option>}{!privateOnly&&<option value="human">{other.name} · Human</option>}</select></label></div><div className="message-list" ref={list} aria-live="polite">{messages.length===0&&!replying?<p className="muted">No messages in this conversation yet.</p>:messages.map(m=><article id={`message-${m.id}`} key={m.id} className={`message ${m.author.id===me.id?'own-message':''}`}><div className="message-author">{m.author.kind==='ai'&&<Icon name="agent" size={24}/>}<strong>{m.author.name}</strong><small>{m.author.kind==='ai'?'AI':'Human'} · {new Date(m.created_at).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}</small></div><div className="message-bubble">{m.text}{m.attachments.map(id=>{const source=snapshot.sources.find(item=>item.id===id);return source?<CitationLink key={id} citation={{source_id:source.id,source_hash:source.hash,label:source.name,locator:{}}}/>:<small key={id}>Attachment unavailable</small>;})}{m.citations.map(c=><CitationLink key={c.label} citation={c}/>)}</div></article>)}
  {audience==='private_ai'&&replying&&<article className="message" aria-busy="true"><div className="message-author"><Icon name="agent" size={24}/><strong>Relay assistant</strong><small>AI · replying…</small></div><div className="message-bubble">{streaming||'…'}</div></article>}</div>
 {preview&&<div className="confirm-panel"><h3>Preview message to {other.name}</h3><p>{text}</p>{attachments.length>0&&<ul>{snapshot.sources.filter(source=>attachments.includes(source.id)).map(source=><li key={source.id}>{source.name}</li>)}</ul>}<p className="muted">Only this text and explicitly selected documents will be included. Simulated delivery.</p><Button variant="outline" onClick={()=>setPreview(false)} disabled={busy}>Keep editing</Button></div>}
 {audience==='private_ai'&&children}{chatError&&audience==='private_ai'&&<p className="feedback feedback-error" role="alert">{chatError}</p>}<div className="chat-attachments"><Button variant="outline" aria-expanded={choosing} disabled={busy||replying||attachableSources.length===0} onClick={()=>setChoosing(!choosing)}>Attach from documents{attachments.length?` (${attachments.length})`:``}</Button>{choosing&&<fieldset><legend>Select documents for this message</legend>{attachableSources.map(source=><label className="check-row" key={source.id}><input type="checkbox" checked={attachments.includes(source.id)} onChange={event=>{setAttachments(event.target.checked?[...attachments,source.id]:attachments.filter(id=>id!==source.id));setPreview(false);}}/>{source.name}</label>)}</fieldset>}{audience==='human'&&role==='founder'&&<small>Only documents already shared with {other.name} can be attached. Share new originals through a packet handoff first.</small>}</div><form className="composer" onSubmit={e=>{void send(e);}}><label className="sr-only" htmlFor={`message-${large?'main':'side'}`}>Message {audience==='human'?other.name:'Relay'}</label><textarea id={`message-${large?'main':'side'}`} value={text} maxLength={8000} placeholder={audience==='human'?`Message ${other.name}…`:'Ask Relay or answer a question…'} onChange={e=>{setText(e.target.value);setPreview(false);}} onKeyDown={e=>{if(audience==='private_ai'&&e.key==='Enter'&&!e.shiftKey){e.preventDefault();if(!busy&&!replying&&text.trim())void send();}}} disabled={busy||replying}/><div className="composer-actions">{replying?<Button variant="outline" onClick={()=>stream.current?.abort()}>Stop</Button>:<Button type="submit" disabled={busy||!text.trim()}>{audience==='human'?(preview?'Confirm simulated send':'Preview message'):'Send'}</Button>}</div></form>
 <p className="conversation-footnote">{audience==='human'?<><Badge>Local demo</Badge> Saved in this browser. Delivery is simulated; nothing is sent to a real person.</>:<><Badge>Live AI</Badge> Replies come from Relay's assistant on Bedrock. History is saved in this browser.{role==='founder'?' Revenue and reserve answers also update the demo draft.':''}</>}</p></section>;
}
