import { useEffect, useState } from 'react';
import { useLocation, useSearchParams } from 'react-router-dom';
import type { ReactNode, FormEvent } from 'react';
import { useDraft, useRelay } from './context';
import { fileContentBase64 } from './intake';
import { AgentStatus, Badge, Button, CitationLink, Icon } from './ui';
export function Conversation({large=false,allowUpload=false,humanOnly=false,privateOnly=false,children}:{children?:ReactNode;large?:boolean;allowUpload?:boolean;humanOnly?:boolean;privateOnly?:boolean}):ReactNode{
 const {snapshot,role,busy,run}=useRelay();const [params]=useSearchParams();const [audience,setAudience]=useState<'private_ai'|'human'>(!privateOnly&&(humanOnly||params.get('audience')==='human')?'human':'private_ai');const [text,setText]=useDraft('message:'+snapshot?.id+':'+audience);const [preview,setPreview]=useState(false);const [file,setFile]=useState<File|null>(null);const [reading,setReading]=useState(false);const [fileError,setFileError]=useState<string|null>(null);
 const [attachments,setAttachments]=useState<string[]>([]);const [choosing,setChoosing]=useState(false);
 const location=useLocation();
 useEffect(()=>{if(location.hash===`#message-${large?'main':'side'}`){const composer=document.getElementById(`message-${large?'main':'side'}`);composer?.focus();composer?.scrollIntoView?.({block:'center'});}},[location,large]);
 useEffect(()=>{if(!privateOnly&&params.get('audience')==='human'){setAudience('human');setAttachments([]);setChoosing(false);setPreview(false);}},[params,privateOnly]);
 useEffect(()=>{const id=params.get('message');if(id)document.getElementById('message-'+id)?.scrollIntoView?.({block:'center'});},[params,snapshot]);
 if(!snapshot)return null;const me=role==='founder'?snapshot.founder:snapshot.advisors[0];const other=role==='founder'?snapshot.advisors[0]:snapshot.founder;
 const attachableSources=snapshot.sources.filter(source=>audience==='private_ai'||role==='advisor'||snapshot.grants.some(grant=>grant.advisor_id===other.id&&grant.source_ids.includes(source.id)));
 const messages=snapshot.messages.filter(m=>audience==='private_ai'?m.audience.kind==='private_ai':m.audience.kind==='human');
 const send=async(e?:FormEvent):Promise<void>=>{e?.preventDefault();if(audience==='human'&&!preview){setPreview(true);return;}const ok=await run({kind:'message',expected_revision:snapshot.revision,text,attachments,audience:audience==='private_ai'?{kind:'private_ai'}:{kind:'human',recipient_id:other.id},confirmed:audience==='human'});if(ok){setText('');setPreview(false);setAttachments([]);setChoosing(false);}};
 const addSource=async():Promise<void>=>{if(!file||reading)return;setReading(true);setFileError(null);try{const content_base64=await fileContentBase64(file);const ok=await run({kind:'upload',expected_revision:snapshot.revision,name:file.name,mime_type:file.type,bytes:file.size,content_base64});if(ok)setFile(null);}catch(error:unknown){setFileError(error instanceof Error?error.message:'Unable to read the selected file.');}finally{setReading(false);}};
 return <section className={`panel conversation ${large?'conversation-large':''}`} aria-label="Conversation"><AgentStatus/><div className="audience-control"><label>Audience<select aria-label="Message audience" value={audience} onChange={e=>{setAudience(e.target.value as 'private_ai'|'human');setPreview(false);setAttachments([]);setChoosing(false);}} disabled={busy}>{!humanOnly&&<option value="private_ai">Private AI conversation</option>}{!privateOnly&&<option value="human">{other.name} · Human</option>}</select></label></div><div className="message-list" aria-live="polite">{messages.length===0?<p className="muted">No messages in this conversation yet.</p>:messages.map(m=><article id={`message-${m.id}`} key={m.id} className={`message ${m.author.id===me.id?'own-message':''}`}><div className="message-author">{m.author.kind==='ai'&&<Icon name="agent" size={24}/>}<strong>{m.author.name}</strong><small>{m.author.kind==='ai'?'AI':'Human'} · {new Date(m.created_at).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}</small></div><div className="message-bubble">{m.text}{m.attachments.map(id=>{const source=snapshot.sources.find(item=>item.id===id);return source?<CitationLink key={id} citation={{source_id:source.id,source_hash:source.hash,label:source.name,locator:{}}}/>:<small key={id}>Attachment unavailable</small>;})}{m.citations.map(c=><CitationLink key={c.label} citation={c}/>)}</div></article>)}</div>
 {preview&&<div className="confirm-panel"><h3>Preview message to {other.name}</h3><p>{text}</p>{attachments.length>0&&<ul>{snapshot.sources.filter(source=>attachments.includes(source.id)).map(source=><li key={source.id}>{source.name}</li>)}</ul>}<p className="muted">Only this text and explicitly selected documents will be included. Simulated delivery.</p><Button variant="outline" onClick={()=>setPreview(false)} disabled={busy}>Keep editing</Button></div>}
 {audience==='private_ai'&&children}<div className="chat-attachments"><Button variant="outline" aria-expanded={choosing} disabled={busy||attachableSources.length===0} onClick={()=>setChoosing(!choosing)}>Attach from documents{attachments.length?` (${attachments.length})`:``}</Button>{choosing&&<fieldset><legend>Select documents for this message</legend>{attachableSources.map(source=><label className="check-row" key={source.id}><input type="checkbox" checked={attachments.includes(source.id)} onChange={event=>{setAttachments(event.target.checked?[...attachments,source.id]:attachments.filter(id=>id!==source.id));setPreview(false);}}/>{source.name}</label>)}</fieldset>}{audience==='human'&&role==='founder'&&<small>Only documents already shared with {other.name} can be attached. Share new originals through a packet handoff first.</small>}</div><form className="composer" onSubmit={e=>{void send(e);}}><label className="sr-only" htmlFor={`message-${large?'main':'side'}`}>Message {audience==='human'?other.name:'Relay'}</label><textarea id={`message-${large?'main':'side'}`} value={text} maxLength={8000} placeholder={audience==='human'?`Message ${other.name}…`:'Ask Relay or answer a question…'} onChange={e=>{setText(e.target.value);setPreview(false);}} disabled={busy}/><div className="composer-actions">{allowUpload&&role==='founder'&&<label className="attachment-label"><Icon name="attach" size={20}/> Add sources<input type="file" aria-label="Attach a source" onChange={e=>{setFile(e.target.files?.[0]??null);e.target.value='';}} disabled={busy}/></label>}<Button type="submit" disabled={busy||!text.trim()}>{audience==='human'?(preview?'Confirm simulated send':'Preview message'):'Send to simulated AI'}</Button></div></form>
 {file&&<div className="confirm-panel"><strong>Selected locally: {file.name}</strong><p>{Math.round(file.size/1024)} KB · Add actual bytes to this browser only. UTF-8 text and CSV previews are supported; PDF and binary extraction is unavailable. Maximum 10 MB.</p>{fileError&&<p role="alert">{fileError}</p>}<div className="row"><Button disabled={busy||reading} onClick={()=>{void addSource();}}>Add source locally</Button><Button disabled={busy||reading} variant="outline" onClick={()=>{setFile(null);setFileError(null);}}>Cancel attachment</Button></div></div>}
 <p className="conversation-footnote"><Badge>Local demo</Badge> Saved in this browser and shared with its same-origin tabs. {audience==='human'?'Delivery is simulated; nothing is sent to a real person.':role==='founder'?'Private numeric revenue and reserve answers prepare a local draft; general AI responses require a backend.':'Only authorized shared documents are available. General AI responses require a backend.'}</p></section>;
}
