import { describe,it,expect } from 'vitest';
import { EventReplay } from './events';
import type { CaseEvent } from './events';
import { createFixture } from './fixtures';
describe('proposed event replay contract',()=>{
 it('orders transactions and rejects older entity revisions within one batch',()=>{const s=createFixture();const replay=new EventReplay(s);const base={type:'source.updated' as const,case_id:s.id,occurred_at:'2026-10-02T18:00:00Z'};const newer:CaseEvent={...base,event_id:'new',cursor:'latest',case_revision:3,data:{source:{...s.sources[0],revision:3,name:'New name'}}};const older:CaseEvent={...base,event_id:'old',cursor:'earlier',case_revision:2,data:{source:{...s.sources[0],revision:2,name:'Old name'}}};const result=replay.applyBatch([newer,older]);expect(result.sources.find(item=>item.id===s.sources[0].id)?.name).toBe('New name');expect(result.event_cursor).toBe('latest');replay.applyBatch([{...older,event_id:'stale-entity',case_revision:4,data:{source:{...s.sources[0],revision:1}}}]);expect(replay.snapshot().sources.find(item=>item.id===s.sources[0].id)?.revision).toBe(3);});
 it('does not partially apply a batch containing another case',()=>{const s=createFixture();const replay=new EventReplay(s);const event:CaseEvent={type:'tasks.updated',event_id:'task',cursor:'next',case_id:s.id,case_revision:2,occurred_at:'2026-10-02T18:00:00Z',data:{tasks:[]}};expect(()=>replay.applyBatch([event,{...event,event_id:'wrong',case_id:'other'}])).toThrow('another case');expect(replay.snapshot()).toEqual(s);});
 it('deduplicates replay and applies sibling events at one revision',()=>{const s=createFixture();const replay=new EventReplay(s);const event:CaseEvent={type:'case.updated',event_id:'e1',cursor:'cursor-2',case_id:s.id,case_revision:2,occurred_at:'2026-10-02T18:00:00Z',data:{status:'Draft ready',ui_state:'Idle',activity:null,current_packet_version_id:s.current_packet_version_id}};const sibling:CaseEvent={...event,type:'tasks.updated',event_id:'e2',cursor:'cursor-3',data:{tasks:[]}};expect(replay.applyBatch([event,sibling,event]).tasks).toEqual([]);expect(replay.snapshot().event_cursor).toBe('cursor-3');expect(replay.applyBatch([{...event,event_id:'old',case_revision:1}]).revision).toBe(2);});
 it('rejects cross-case events and demands a resync for changed sharing',()=>{const s=createFixture();const replay=new EventReplay(s);const e:CaseEvent={type:'sharing.updated',event_id:'e1',cursor:'x',case_id:s.id,case_revision:2,occurred_at:'2026-10-02T18:00:00Z',data:{grant:s.grants[0]}};expect(()=>replay.applyBatch([{...e,case_id:'other'}])).toThrow('another case');expect(()=>replay.applyBatch([e])).toThrow('Sharing scope changed');});
});
