import { useState } from 'react';
import type { ReactNode } from 'react';
import { useDraft, useRelay } from './context';
import { Badge, Button, CitationLink, Panel } from './ui';
import type { PacketVersion } from './types';
export function ReviewControls({packet}:{packet:PacketVersion}):ReactNode{
 const {snapshot,role,busy,run}=useRelay();const [text,setText]=useDraft('review:'+packet.id,'Can you confirm your reserve target and which 2026 annual revenue figure is correct?');const [confirmApproval,setConfirmApproval]=useState(false);const [previewId,setPreviewId]=useState<string|null>(null);
 if(!snapshot||role!=='advisor')return null;const version={expected_revision:snapshot.revision,packet_version_id:packet.id,packet_hash:packet.hash};const flags=snapshot.flags.filter(f=>f.packet_version_id===packet.id);const q=snapshot.clarifications.find(q=>q.id===previewId);const matching=q&&q.text===text&&q.packet_version_id===packet.id&&q.status==='preview';
 const createPreview=async():Promise<void>=>{const ok=await run({kind:'preview',...version,text,recipient_id:snapshot.founder.id,citations:flags.flatMap(f=>f.citations)});if(ok)setPreviewId('latest');};
 // Newly created preview is identified on the next authoritative snapshot.
 const active=previewId==='latest'?snapshot.clarifications.filter(c=>c.text===text&&c.packet_version_id===packet.id&&c.status==='preview').at(-1):q;
 const ready=Boolean((matching||previewId==='latest')&&active?.status==='preview'&&active.text===text&&active.packet_version_id===packet.id);
 const sent=snapshot.clarifications.filter(item=>item.packet_version_id===packet.id&&item.status==='sent'&&!snapshot.reviews.some(review=>review.clarification_id===item.id&&review.decision==='questions_returned')).at(-1);
 return <Panel title="Review this version" className="review-controls"><Badge>v{packet.version} · Exact version decision</Badge><div className="flag-list">{flags.map(f=><div className="flag" key={f.id}><strong>{f.kind==='missing'?'Missing detail':'Source conflict'}</strong><p>{f.text}</p>{f.citations.map(c=><CitationLink key={c.label} citation={c}/>)}</div>)}</div><label>Draft question to {snapshot.founder.name}<textarea value={text} maxLength={8000} onChange={e=>{setText(e.target.value);setPreviewId(null);}} disabled={busy}/></label><Button variant="outline" disabled={busy||!text.trim()} onClick={()=>{void createPreview();}}>Preview questions</Button>
 {ready&&active&&<div className="confirm-panel"><h3>Question preview</h3><p>To {active.recipient.name} · packet v{packet.version}</p><p>{active.text}</p><div className="stack"><Button disabled={busy} onClick={()=>{void run({kind:'send',...version,clarification_id:active.id,clarification_revision:active.revision,text:active.text,recipient_id:active.recipient.id}).then(ok=>{if(ok)setPreviewId(null);});}}>Confirm simulated send</Button><Button variant="outline" disabled={busy} onClick={()=>{void run({kind:'review',...version,decision:'questions_returned',clarification_id:active.id,clarification_revision:active.revision}).then(ok=>{if(ok)setPreviewId(null);});}}>Return review with these questions</Button><Button variant="subtle" onClick={()=>setPreviewId(null)} disabled={busy}>Cancel preview</Button></div></div>}
 {sent&&<div className="confirm-panel"><h3>Question already sent to {sent.recipient.name}</h3><p>{sent.text}</p><p>Return this review using the existing question. No duplicate message will be sent.</p><Button variant="outline" disabled={busy} onClick={()=>{void run({kind:'review',...version,decision:'questions_returned',clarification_id:sent.id,clarification_revision:sent.revision});}}>Return review with sent question</Button></div>}
 <hr/>{confirmApproval?<div className="confirm-panel"><h3>Approve packet v{packet.version}?</h3><p>Only this exact version is covered. Source flags remain visible. This approval is simulated and is not saved to a backend.</p><Button disabled={busy} onClick={()=>{void run({kind:'review',...version,decision:'approved'}).then(ok=>{if(ok)setConfirmApproval(false);});}}>Confirm simulated approval of v{packet.version}</Button><Button variant="subtle" onClick={()=>setConfirmApproval(false)} disabled={busy}>Cancel approval</Button></div>:<Button disabled={busy||packet.status==='approved'} onClick={()=>setConfirmApproval(true)}>Review approval of v{packet.version}</Button>}</Panel>;
}
export function HandoffControls({packet}:{packet:PacketVersion}):ReactNode{
 const {snapshot,role,busy,run}=useRelay();const [open,setOpen]=useState(false);const [ids,setIds]=useState<string[]>([]);if(!snapshot||role!=='founder')return null;
 return <Panel title="Share for advisor review"><p>Confirm the exact version and originals that {snapshot.advisors[0].name} may see.</p>{!open?<Button onClick={()=>setOpen(true)}>Preview handoff of v{packet.version}</Button>:<div className="confirm-panel"><h3>{snapshot.advisors[0].name} · packet v{packet.version}</h3><p>Private AI messages are excluded.</p>{snapshot.sources.map(s=><label className="check-row" key={s.id}><input type="checkbox" checked={ids.includes(s.id)} onChange={e=>setIds(e.target.checked?[...ids,s.id]:ids.filter(id=>id!==s.id))}/>{s.name}</label>)}<div className="row"><Button disabled={busy} onClick={()=>{void run({kind:'handoff',expected_revision:snapshot.revision,packet_version_id:packet.id,packet_hash:packet.hash,advisor_id:snapshot.advisors[0].id,source_ids:ids,message_ids:[]}).then(ok=>{if(ok)setOpen(false);});}}>Confirm simulated handoff</Button><Button variant="outline" disabled={busy} onClick={()=>setOpen(false)}>Cancel handoff</Button></div></div>}</Panel>;
}
