import type { ButtonHTMLAttributes, ReactNode } from 'react';
import { useRelay } from './context';
export function Button({variant='primary',className='',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'outline'|'subtle'}):ReactNode{return <button type="button" className={`button button-${variant} ${className}`} {...props}/>;}
export function Panel({children,className='',title}:{children:ReactNode;className?:string;title?:string}):ReactNode{return <section className={`panel ${className}`}>{title&&<h2>{title}</h2>}{children}</section>;}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:'neutral'|'attention'|'success'}):ReactNode{return <span className={`badge badge-${tone}`}>{children}</span>;}
export function Icon({name,size=22}:{name:'home'|'folder'|'file'|'call'|'settings'|'clients'|'review'|'search'|'agent'|'attach'|'message';size?:number}):ReactNode{return <span className="icon" style={{width:size,height:size}}><img src={`/assets/${name === 'file' && size <= 18 ? 'file-citation' : name === 'file' && size === 20 ? 'file-navigation' : name === 'file' && [25,26,27,32].includes(size) ? 'file-'+size : name === 'folder' && size === 35 ? 'folder-35' : name}.svg`} alt=""/></span>;}
export function PageTitle({title,subtitle,children}:{title:string;subtitle?:string;children?:ReactNode}):ReactNode{return <header className="page-title"><div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{children}</header>;}
export function EmptyState({title,children}:{title:string;children?:ReactNode}):ReactNode{return <div className="empty-state"><Icon name="folder" size={32}/><h2>{title}</h2>{children}</div>;}
export function AgentStatus():ReactNode{return <div className="agent-status"><Icon name="agent" size={38}/><div><strong>Relay assistant</strong><small>One AI assistant</small></div></div>;}
export function ScreenState({children}:{children:ReactNode}):ReactNode{const {snapshot,loading,error,refresh}=useRelay();if(loading&&!snapshot)return <div className="empty-state" role="status">Loading workspace…</div>;if(!snapshot)return <EmptyState title="Workspace unavailable"><p role="alert">{error}</p><Button onClick={refresh}>Retry loading</Button></EmptyState>;return children;}
