import type { ButtonHTMLAttributes, ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { useRelay } from './context';
import type { Citation, PacketVersion, Source } from './types';
export function Button({variant='primary',className='',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'outline'|'subtle'}):ReactNode{return <button type="button" className={`button button-${variant} ${className}`} {...props}/>;}
export function Panel({children,className='',title}:{children:ReactNode;className?:string;title?:string}):ReactNode{return <section className={`panel ${className}`}>{title&&<h2>{title}</h2>}{children}</section>;}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:'neutral'|'attention'|'success'}):ReactNode{return <span className={`badge badge-${tone}`}>{children}</span>;}
export function Icon({name,size=22}:{name:'home'|'folder'|'file'|'call'|'settings'|'clients'|'review'|'search'|'agent'|'attach';size?:number}):ReactNode{return <span className="icon" style={{width:size,height:size}}><img src={`/assets/${name === 'file' && size <= 18 ? 'file-citation' : name === 'file' && size === 20 ? 'file-navigation' : name === 'file' && [25,26,27,32].includes(size) ? 'file-'+size : name === 'folder' && size === 35 ? 'folder-35' : name}.svg`} alt=""/></span>;}
export function PageTitle({title,subtitle,children}:{title:string;subtitle?:string;children?:ReactNode}):ReactNode{return <header className="page-title"><div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{children}</header>;}
export function EmptyState({title,children}:{title:string;children?:ReactNode}):ReactNode{return <div className="empty-state"><Icon name="folder" size={32}/><h2>{title}</h2>{children}</div>;}
export function CitationLink({citation}:{citation:Citation}):ReactNode{const {role}=useRelay();const target=citation.source_kind==='message'?`${role==='founder'?'/founder/chat':'/advisor/documents'}?audience=human&message=${encodeURIComponent(citation.source_id)}#message-${citation.source_id}`:`${role==='founder'?'/founder/sources':'/advisor/clients'}?source=${encodeURIComponent(citation.source_id)}`;return <Link className="citation" to={target}><Icon name="file" size={18}/>{citation.label}</Link>;}
export function AgentStatus():ReactNode{const {snapshot}=useRelay();return <div className="agent-status"><Icon name="agent" size={38}/><div><strong>Relay assistant</strong><small>One AI assistant</small></div><Badge tone={snapshot?.ui_state==='Needs input'?'attention':'neutral'}>{snapshot?.ui_state??'Idle'}</Badge></div>;}
export function SourcePreview({source}:{source:Source}):ReactNode{return <Panel title="Source preview"><div className="row"><Icon name="file" size={32}/><h3>{source.name}</h3><Badge>{source.content_base64===undefined?'Original · Synthetic fixture':'Original · Stored locally'}</Badge></div>{source.excerpt&&<pre className="source-excerpt">{source.excerpt}</pre>}<p className="muted">{source.content_base64===undefined?'Synthetic fixture excerpt. No original file bytes are available.':source.error??'Actual UTF-8 text extracted locally. Original bytes are retained in this browser.'}</p>{source.content_base64!==undefined&&<a className="button button-outline" href={`data:${source.mime_type};base64,${source.content_base64}`} download={source.name}>Download local original</a>}{source.citations.map(c=><CitationLink key={c.label} citation={c}/>)}</Panel>;}
export function PacketPreview({packet,compact=false}:{packet:PacketVersion;compact?:boolean}):ReactNode{return <section className={`packet-preview ${compact?'compact':''}`} aria-label={`Packet version ${packet.version} preview`}><div className="document-toolbar"><Icon name="file"/><strong>{packet.title} · v{packet.version}</strong><Badge tone={packet.status==='approved'?'success':'neutral'}>{packet.status.replaceAll('_',' ')} · simulated</Badge></div><article className="paper"><h2>Northstar Labs</h2><h3>Founder planning packet</h3><p className="muted">Prepared for Alex Morgan · Synthetic data</p><hr/><div className="packet-text">{packet.content.split('\n').map((line,i)=>/^\d\./.test(line)?<h4 key={i}>{line}</h4>:<p key={i}>{line||'\u00a0'}</p>)}</div><div className="packet-evidence">{packet.citations.map(citation=><CitationLink key={citation.source_id+ citation.label} citation={citation}/>)}</div><footer>Draft for discussion · v{packet.version} · Synthetic data</footer></article></section>;}
export function ScreenState({children}:{children:ReactNode}):ReactNode{const {snapshot,loading,error,refresh}=useRelay();if(loading&&!snapshot)return <div className="empty-state" role="status">Loading workspace…</div>;if(!snapshot)return <EmptyState title="Workspace unavailable"><p role="alert">{error}</p><Button onClick={refresh}>Retry loading</Button></EmptyState>;return children;}
